-- Add missing balance columns to leave_balances if they don't exist
ALTER TABLE public.leave_balances 
ADD COLUMN IF NOT EXISTS annual_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS emergency_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS maternity_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS paternity_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS compassionate_balance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS replacement_balance INTEGER DEFAULT 0;

-- Ensure other columns from the definition are present too just in case
ALTER TABLE public.leave_balances
ADD COLUMN IF NOT EXISTS annual_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS annual_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS annual_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS medical_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS emergency_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS emergency_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS emergency_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS maternity_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS maternity_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS maternity_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS paternity_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS paternity_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS paternity_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS compassionate_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS compassionate_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS compassionate_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS replacement_entitled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS replacement_taken INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS replacement_pending INTEGER DEFAULT 0,

ADD COLUMN IF NOT EXISTS unpaid_taken INTEGER DEFAULT 0;
