-- Improvements to create_public_order
-- Handles "Optimistic" Customer IDs generated by the frontend that don't exist in DB yet.
-- Prevents Foreign Key Violations by looking up or creating the customer on the fly.

create or replace function public.create_public_order(data jsonb)
returns setof orders
language plpgsql
security definer
set search_path = public
as $$
declare
  new_record orders%rowtype;
  valid_customer_id uuid;
begin
  -- 1. Populate record from JSON (missing fields become NULL)
  new_record := jsonb_populate_record(null::orders, data);

  -- 2. Handle Defaults (from prev fix)
  if new_record.id is null then new_record.id := gen_random_uuid(); end if;
  if new_record.created_at is null then new_record.created_at := now(); end if;
  if new_record.updated_at is null then new_record.updated_at := now(); end if;
  
  -- Enum/Text defaults
  if new_record.status is null then new_record.status := 'pending'; end if;
  if new_record.order_type is null then new_record.order_type := 'takeaway'; end if;
  if new_record.items is null then new_record.items := '[]'::jsonb; end if;
  
  -- Numeric defaults
  if new_record.subtotal is null then new_record.subtotal := 0; end if;
  if new_record.discount is null then new_record.discount := 0; end if;
  if new_record.tax is null then new_record.tax := 0; end if;
  if new_record.total is null then new_record.total := 0; end if;
  
  -- Order Number Fallback
  if new_record.order_number is null then 
    new_record.order_number := to_char(now(), 'YYMMDDHH24MISS');
  end if;

  -- 3. SMART CUSTOMER LINKING
  -- Problem: Frontend sends a local UUID that doesn't exist in DB yet (FK Violation).
  -- Solution: Validate ID. If invalid, find by phone. If not found, create new.
  
  if new_record.customer_id is not null then
    -- Check if this ID actually exists
    select id into valid_customer_id from customers where id = new_record.customer_id;
    
    if valid_customer_id is null then
      -- ID provided but NOT found. Assume it's an optimistic/local ID. Discard it.
      new_record.customer_id := null;
    end if;
  end if;

  -- If we don't have a valid ID yet, try to find by phone
  if new_record.customer_id is null and new_record.customer_phone is not null then
     select id into valid_customer_id from customers where phone = new_record.customer_phone limit 1;
     if valid_customer_id is not null then
       new_record.customer_id := valid_customer_id;
     end if;
  end if;

  -- If STILL null, and we have enough info, create a NEW customer
  if new_record.customer_id is null and new_record.customer_name is not null then
    -- Insert new customer and get ID
    insert into customers (id, name, phone, segment, created_at)
    values (gen_random_uuid(), new_record.customer_name, new_record.customer_phone, 'new', now())
    returning id into new_record.customer_id;
  end if;

  -- 4. Insert the fully populated order
  insert into orders values (new_record.*)
  returning * into new_record;
  
  return next new_record;
end;
$$;

-- Ensure permissions
grant execute on function public.create_public_order(jsonb) to anon;
grant execute on function public.create_public_order(jsonb) to authenticated;
grant execute on function public.create_public_order(jsonb) to service_role;
