import { StockItem } from './types';

export const MOCK_STOCK: StockItem[] = [
  {
    id: '1',
    name: 'Ayam',
    category: 'Protein',
    currentQuantity: 45,
    minQuantity: 50,
    unit: 'kg',
    cost: 12.00,
    supplier: 'Supplier A',
  },
  {
    id: '2',
    name: 'Nasi',
    category: 'Staple',
    currentQuantity: 80,
    minQuantity: 100,
    unit: 'kg',
    cost: 5.00,
    supplier: 'Supplier B',
  },
  {
    id: '3',
    name: 'Daging',
    category: 'Protein',
    currentQuantity: 30,
    minQuantity: 40,
    unit: 'kg',
    cost: 35.00,
    supplier: 'Supplier A',
  },
  {
    id: '4',
    name: 'Telur',
    category: 'Protein',
    currentQuantity: 120,
    minQuantity: 150,
    unit: 'pcs',
    cost: 0.50,
    supplier: 'Supplier C',
  },
  {
    id: '5',
    name: 'Sambal',
    category: 'Condiment',
    currentQuantity: 15,
    minQuantity: 20,
    unit: 'kg',
    cost: 8.00,
    supplier: 'Supplier B',
  },
  {
    id: '6',
    name: 'Burger Bun',
    category: 'Bread',
    currentQuantity: 200,
    minQuantity: 150,
    unit: 'pcs',
    cost: 0.80,
    supplier: 'Supplier D',
  },
  {
    id: '7',
    name: 'Cheese',
    category: 'Dairy',
    currentQuantity: 50,
    minQuantity: 60,
    unit: 'slices',
    cost: 1.20,
    supplier: 'Supplier E',
  },
  {
    id: '8',
    name: 'Teh',
    category: 'Beverage',
    currentQuantity: 5,
    minQuantity: 10,
    unit: 'kg',
    cost: 25.00,
    supplier: 'Supplier B',
  },
  {
    id: '9',
    name: 'Kopi',
    category: 'Beverage',
    currentQuantity: 8,
    minQuantity: 10,
    unit: 'kg',
    cost: 30.00,
    supplier: 'Supplier B',
  },
  {
    id: '10',
    name: 'Cup',
    category: 'Packaging',
    currentQuantity: 500,
    minQuantity: 300,
    unit: 'pcs',
    cost: 0.15,
    supplier: 'Supplier F',
  },
];

export function getLowStockItems(): StockItem[] {
  return MOCK_STOCK.filter(item => item.currentQuantity <= item.minQuantity);
}

